default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: askusers_db

test:
  <<: *default
  database: askusers_test_db

production:
  <<: *default
  database: askusers_production
  username: askusers
  password: <%= ENV["ASKUSERS_DATABASE_PASSWORD"] %>
